mapping: "/home/fengchr/staff/laichp_RNAseq_6_19/data/mapping.csv"
reference: "/Yol_Data/resources/Gencode_human_ref/GRCh38.p13.genome.fa"
intervals_list: "/home/fengchr/staff/RNA_edit_pipeline/test/reference/human.intervals.list"
annotation_gtf: "/Yol_Data/resources/Gencode_human_ref/gencode.v42.chr_patch_hapl_scaff.annotation.gtf"
STAR:
  STARref: "/Yol_Data/resources/Gencode_human_ref/hg38_STAR_ref"
  genomeSAindexNbases: 14
  outFilterMultimapNmax: 20
  sjdbOverhang: 150 #read_length - 1
min_sample_count: 2
min_mapping_quality: 20
min_base_quality: 30
maximum_alt_percent_in_control: 0.01
minimum_editing_site_coverage_in_test: 10
sequencelogo_span_len: 5
gtf2bed_field: "exon"
readcommand: "--readFilesCommand zcat "
